import { parseTemplateVariables } from './templateParser';

export type WorkflowFormat = 'claude-skill';

export interface WorkflowExportOptions {
  format: WorkflowFormat;
  packTitle: string;
  prompts: Array<{ text: string; header?: string }>;
}

/**
 * Generate a workflow file from a pack's prompts
 */
export function generateWorkflow(options: WorkflowExportOptions): string {
  switch (options.format) {
    case 'claude-skill':
      return generateClaudeSkill(options);
    default:
      throw new Error(`Unsupported workflow format: ${options.format}`);
  }
}

/**
 * Get the skill directory name (slug) for a pack title
 * Follows Claude skill naming rules: lowercase, hyphens, max 64 chars
 */
export function getSkillDirName(packTitle: string): string {
  return packTitle
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 64) || 'workflow';
}

function generateClaudeSkill({ packTitle, prompts }: WorkflowExportOptions): string {
  const lines: string[] = [];
  const slug = getSkillDirName(packTitle);

  // Build step summary for description
  const stepNames = prompts.map((p, i) => p.header || `Step ${i + 1}`);
  const stepSummary = stepNames.join(' → ');

  // YAML frontmatter
  lines.push('---');
  lines.push(`name: ${slug}`);
  lines.push(`description: "Multi-step prompt workflow: ${stepSummary}. Exported from PromptPack."`);
  lines.push('disable-model-invocation: true');
  lines.push('---');
  lines.push('');

  // Title
  lines.push(`# ${packTitle}`);
  lines.push('');
  lines.push('A multi-step prompt workflow where each step builds on the previous output.');
  lines.push('');

  // Collect all unique template variables across all prompts
  const allVars = new Set<string>();
  for (const prompt of prompts) {
    for (const v of parseTemplateVariables(prompt.text)) {
      allVars.add(v);
    }
  }

  // Variables section (before steps so agent sees them first)
  if (allVars.size > 0) {
    lines.push('## Variables');
    lines.push('');
    lines.push('This workflow uses template variables. Before executing any step, ask the user to provide a value for each variable listed below. The variable name describes what value is needed.');
    lines.push('');
    lines.push('| Variable | Value |');
    lines.push('|----------|-------|');
    for (const v of allVars) {
      lines.push(`| ${v} | _____ |`);
    }
    lines.push('');
    lines.push('Replace every `{VariableName}` placeholder in the prompts below with the value the user provides.');
    lines.push('');
  }

  // Workflow steps
  lines.push('## Workflow Steps');
  lines.push('');

  for (let i = 0; i < prompts.length; i++) {
    const prompt = prompts[i];
    const stepNum = i + 1;
    const title = prompt.header || `Step ${stepNum}`;

    lines.push(`### Step ${stepNum}: ${title}`);
    lines.push('');

    if (i === 0) {
      lines.push('Execute the following prompt:');
    } else {
      lines.push('Using the output from the previous step as context, execute the following prompt:');
    }

    lines.push('');
    lines.push('```');
    lines.push(prompt.text);
    lines.push('```');
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push('- Each step\'s output should be provided as context when executing the next step.');
  lines.push('- Generated by PromptPack.');
  lines.push('');

  return lines.join('\n');
}
